### ISSUE TITLE
Web Monetization not limited to Coil

### ISSUE THREAD

**Issue by jaller94** [lopis/regresso#2]
https://github.com/lopis/regresso/blob/ccb3abd20c7268c98bd39d7716aef2850750e9fd/src/html/index.html#L40

While Coil is the service collaborating with js13kgames, it is not the only service that allows people to use Web Monetization and pay you while playing.

### Expected
The text mentions Web Monetization, because that is the underlying standard all users will know.

### Actual
The text mentions Coil, which is just one service to use Web Monetization.

**Comment by lopis** [comment]
You are right. Wanna open a PR to fix that? :)
